services:
  - type: web
    name: oildropminer02
    env: docker
    buildCommand: "docker build -t my-php-app ."
    startCommand: "docker run -p ${PORT}:8080 my-php-app"
    envVars:
      - key: DATABASE_URL
        value: "postgres://oildropminer_db_user:WXzD1SqGI9Vx8nZ966VK4dUNH1p6f2QGWXzD1SqGI9Vx8nZ966VK4dUNH1p6f2QG@dpg-cv4gtnij1k6c73bjrrhg-a.oregon-postgres.render.com:5432/oildropminer_db"
    regions:
      - oregon