services:
  - type: web
    name: oildropminer02
    env: php
    buildCommand: "echo 'No build required for PHP'"
    startCommand: "php -S 0.0.0.0:${PORT} telegram.php"
    envVars:
      - key: DATABASE_URL
        value: "postgres://oildropminer_db_user:WXzD1SqGI9Vx8nZ966VK4dUNH1p6f2QGWXzD1SqGI9Vx8nZ966VK4dUNH1p6f2QG@dpg-cv4gtnij1k6c73bjrrhg-a.oregon-postgres.render.com:5432/oildropminer_db"
    regions:
      - oregon